apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssue
metadata: 
  name:  letsencrypt-prod
spec: 
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "samo59gog@gmail.com"
    privatekeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress: 
            class: nginx